version: "3.7"

services:
    docker-kongkow: 
        container_name: docker-kongkow
        build: 
            context: "."
            dockerfile: Dockerfile
        volumes: 
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        restart: always
        ports:
            - "10100:80"